### ISSUE TITLE
Type 'any' is not a constructor function type.

### ISSUE THREAD

**Issue by milanjya** [Riron/ionic-img-viewer#59]
![image](https://cloud.githubusercontent.com/assets/14172674/26749928/7f0c93b6-4849-11e7-9232-096a2a5acbd2.png)

Help.

**Comment by milanjya** [comment]
my ionic is v3.3.0
can it work?

**Comment by gunjank** [comment]
I was able to fix this in local by using correct import  path "drag-gesture. 

 import { PanGesture } from '../../gestures/drag-gesture';

**Comment by Riron** [comment]
It should be fixed in latest release - please upgrade.
Thanks !

**Comment by milanjya** [comment]
thank's @Riron  @gunjank

**Comment by smkamranqadri** [comment]
Issue not resolved yet.

`[13:54:35]  typescript: ...de_modules/ionic-img-viewer/dist/es2015/src/image-viewer-transition-gesture.d.ts, line: 6 
            Type 'any' is not a constructor function type. 

       L5:  import { DomController } from 'ionic-angular';
       L6:  export declare class ImageViewerTransitionGesture extends PanGesture {
       L7:      private component;

[13:54:35]  typescript: node_modules/ionic-img-viewer/dist/es2015/src/image-viewer.d.ts, line: 5 
            Type 'any' is not a constructor function type. 

       L4:  import { ImageViewerComponent } from './image-viewer.component';
       L5:  export declare class ImageViewer extends OverlayProxy {
       L6:      private opts;

[13:54:35]  typescript: node_modules/ionic-img-viewer/dist/es2015/src/image-viewer.d.ts, line: 8 
            Cannot find name 'Overlay'. 

       L7:      constructor(app: App, component: typeof ImageViewerComponent, opts: ImageViewerOptions, config: Config, deepLinker: DeepLinker);
       L8:      getImplementation(): Overlay;
`

**Comment by Riron** [comment]
Check your dependencies versions. If the problem persists open a new issue with your detailed versions.

**Comment by smkamranqadri** [comment]
I installed v1 which is working fine but latest version should work.

**Comment by HZooly** [comment]
@Riron last version (2.9.0) still not working, I had to use v1.3.1 with Ionic.
