### ISSUE TITLE
ngc error: Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by longfay** [Riron/ionic-img-viewer#9]
Hi! Thanks for your contribution on the plugin. I am using Ionic2(not the beta one) and when I wanna import your ionic-ing-viewer to my NgModule, there exists an error:

ngc error: Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'

Does anyone have any idea how it comes?
Thanks in advance!

**Comment by Riron** [comment]
Hi, thanks for opening an issue.

Are you importing the module like this `import { IonicImageViewerModule } from 'ionic-img-viewer';` ?

If yes, you can try `import { IonicImageViewerModule } from 'ionic-img-viewer/module';`. This has something to do with rollup configuration in Ionic.

**Comment by longfay** [comment]
Thanks very much for your quick reply Riron!

Yes I am using `import { IonicImageViewerModule } from 'ionic-img-viewer';` in my app.module.ts file.
I tried `import { IonicImageViewerModule } from 'ionic-img-viewer/module';` and also I use the version 1.1.1 of ionic-ing-viewer.

My ionic version is 2.1.0.

Unfortunately, it continues to give out the error message:
ngc error: Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'.
which is the same as the error above. :(

I don't know how can it comes up lol. But thanks for your reply! If you have any other possible solutions please let me know. :)

**Comment by dmastag** [comment]
Same here, I also tried to do the following

Import using
```import { IonicImageViewerModule } from 'ionic-img-viewer/src/module';```

Adding into rollup config
```
plugins: [
        builtins(),
        commonjs({
            include: [
                'node_modules/rxjs/**',
                'node_modules/ionic-img-viewer/**',
            ],
            namedExports: {
                'node_modules/ionic-img-viewer/ionic-img-viewer.js': ['IonicImageViewerModule']
            }
        }),
        nodeResolve({
            module: true,
            jsnext: true,
            main: true,
            browser: true,
            extensions: ['.js']
        }),
        globals(),
        json()
    ]
```

But still getting the same problem

![image](https://cloud.githubusercontent.com/assets/5745805/19542734/00b986e6-969b-11e6-805c-d193a62f54a3.png)

**Comment by Riron** [comment]
You shouldn't have to modify your rollup config.
Do you have the latest `@ionic/app-scripts` installed ? (`"@ionic/app-scripts": "^0.0.36"` in your `package.json`)

**Comment by longfay** [comment]
I have updated to `@ionic/app-scripts": "^0.0.36` in my `package.json`. Same error lol.

**Comment by kadox07** [comment]
i have this problem when run build but with serve comand worked! Help me

**Comment by kadox07** [comment]
I run the command "sudo rm ionic platform ios" and then "sudo add ionic platform ios" and even "sudo ionic build ios". When ancio the application by xcode I get the following error "Plugin Should use a background thread." can you help me? the plug-in version 1.1.1

**Comment by dmastag** [comment]
Am also on 0.0.36 and its still happening
Any information I could provide to help you find the problem?

**Comment by kadox07** [comment]
hello guys, I want to help you! I have solved so: https://github.com/driftyco/ionic-cli/issues/1504. Riron may close this issue and focus on the slide ahhah xD I hope I've helped hello, see you soon

**Comment by dmastag** [comment]
@kadox07 how exactly did you get this working ?
Tried using the --dev and still isn't working for me.

**Comment by hugovl74** [comment]
@kadox07, thank you, works flawlessly!

**Comment by dmastag** [comment]
@kadox07 I did that, and its not working. Its also just a work around isn't it? And its downgrading performance by removing AOT

**Comment by Riron** [comment]
Indeed support for AOT compiling was missing. 
Could you please try the 1.1.2 release ? This should be fixed by now.

**Comment by dmastag** [comment]
Hi @Riron ,
Tried it as per readme and its not working.

Also tried to change the import into:
import { IonicImageViewerModule } from 'ionic-img-viewer/dist/src/module';

And try to update the rollup.

Any idea what I am doing wrong?

![image](https://cloud.githubusercontent.com/assets/5745805/19631419/4fc8eee2-99c6-11e6-9e36-61a475310d02.png)

**Comment by Riron** [comment]
Keep the `import { IonicImageViewerModule } from 'ionic-img-viewer';` import, it's the correct one.

Are you doing a `ionic serve` or a `ionic build` ? Or maybie you have the problem in both cases ?

**Comment by dmastag** [comment]
Noted on the setup.
Its on `ionic serve`

**Comment by gfviegas** [comment]
I'm also having the same issue, using the new version @Riron . It reports me in the console:

main.js:25715 Uncaught Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'

Usin' ionic serve and importing like:

import { IonicImageViewerModule } from 'ionic-img-viewer';

**Comment by dmastag** [comment]
The weird thing is that this is working as expected on a new ionic2 project. But I can't get it to work on an existing project.

**Comment by dmastag** [comment]
I tried to copy the src folder into my Ionic2 App and Imported the module.ts directly. Its is working this way. Sadly I don't really understand how to create npm modules so I can't help or create a pull request.

**Comment by Riron** [comment]
As you're saying, I tried creating a new Ionic2 project and it worked.
It probably has something to do with your build phase or version of dependencies, but I cannot reproduce the bug.

**Comment by niconaso** [comment]
@Riron I think the problem is associated with angular ngc.

**Comment by lingyilun** [comment]
My mistake is the same,
ngc error: Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'
Someone has a solution?

**Comment by niconaso** [comment]
I'm getting the same error on version 1.1.3

`[08:32:49]  Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule' 
[08:32:49]  ngc failed 
[08:32:49]  ionic-app-script task: "build" 
[08:32:49]  Error: Error `

My system info:

> Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.19
Node Version: v6.7.0
Xcode version: Not installed

**Comment by Riron** [comment]
Do you have `@angular/compiler` installed locally ? Under what version ?
It seems to be due to versions mismatch, but i'm cannot be sure yet...

And if you run `ngc` instead of the classic `ionic serve`, could you please post the stack trace here ?
Thanks.

**Comment by niconaso** [comment]
@Riron I have a local @angular/compiler version is 2.1.1
It executes well with `ionic serve` but it fails when I run `ionic build android`. 
I don't know how to compile with **ngc**, could you help me?

**Comment by Riron** [comment]
You can run `node_modules/.bin/ngc`, with double quotes if you're on windows `"node_modules/.bin/ngc"`.

**Comment by niconaso** [comment]
I executed `node_modules/.bin/ngc` and showed me this error:

> Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'
    at /home/nicolas/desarrollo/workspace/runrun-3-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:14078:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/home/nicolas/desarrollo/workspace/runrun-3-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:14063:46)
    at /home/nicolas/desarrollo/workspace/runrun-3-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12865:47
    at Array.forEach (native)
    at analyzeModules (/home/nicolas/desarrollo/workspace/runrun-3-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12864:17)
    at OfflineCompiler.analyzeModules (/home/nicolas/desarrollo/workspace/runrun-3-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12889:18)
    at CodeGenerator.codegen (/home/nicolas/desarrollo/workspace/runrun-3-mobile/node_modules/@angular/compiler-cli/src/codegen.js:121:47)
    at codegen (/home/nicolas/desarrollo/workspace/runrun-3-mobile/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/home/nicolas/desarrollo/workspace/runrun-3-mobile/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
Compilation failed

**Comment by niconaso** [comment]
@Riron I forgot to mention on my previous comment

**Comment by lingyilun** [comment]
@Riron  Thank you, I can already use

**Comment by Riron** [comment]
@lingyilun what do you mean ? It's working now ?

@niconaso thanks for sthe stack trace. It seems that `ngc` cannot locate the module metadata, but the [metadata **ARE** bundled](https://unpkg.com/ionic-img-viewer@1.1.3/dist/src/) into the library, as needed for AOT to work. And it works indeed for most people with RC2...

It might be linked to some `node_modules` version problem but I am not sure.
Maybie the Ionic folks have an idea on what's going on ? @danbucholtz

**Comment by niconaso** [comment]
@Riron Your're welcome! 
I've tested with ionic-app-scripts version 0.0.45 and I doesn't work with `ionic serve` nor `ionic build ...`

This is my system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.19
Node Version: v6.7.0
Xcode version: Not installed

**Comment by niconaso** [comment]
@Riron I think the author of this module https://github.com/fiznool/angular2-elastic could help you this fix this issue

**Comment by lingyilun** [comment]
@Riron  I'm not sure though before my question was 

ngc error: Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'

but when I updated later it's pass and 

into package.json try overwrite your "scripts" with this:
"scripts": {
"build": "ionic-app-scripts build --dev",
"watch": "ionic-app-scripts watch",
"serve:before": "watch",
"emulate:before": "build",
"deploy:before": "build",
"build:before": "build",
"run:before": "build"
}
works flawlessly!

**Comment by Riron** [comment]
Things might be better in `1.1.5`, with https://github.com/Riron/ionic-img-viewer/commit/f0d2b71c1f5f8e9c76cdfb75b1d3cf8c4389a210.

Please tell me if you see any improvement...
Sorry about all that, the path to AOT support is not very clear

**Comment by niconaso** [comment]
@Riron thanks to you! I'll test it when you release the next version. Thanks again!

**Comment by niconaso** [comment]
@Riron it works perfect!! Thank you very much!

**Comment by Riron** [comment]
Finally ! Good to hear 👍 
If nobody complains about it still not working for a few days, i'll close the issue.

**Comment by SealTecH** [comment]
Hi @Riron, I have same problem.. I tried to insert  this into package.json
    "build": "ionic-app-scripts build --dev",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
 
but still have an error 
Uncaught Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'

Information
 Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.7.0
Xcode version: Not installed

Can you help me?

**Comment by Riron** [comment]
The fix is only available for the latest versions: `ionic-angular@2.0.0-rc.3` and `ionic-img-viewer@1.1.5`.
Please upgrade

**Comment by niconaso** [comment]
@Riron bad news! I tested on Ubuntu and it fails again :(

It throws this: 

`[19:19:07]  Error: Error at 
            /home/nicolas/desarrollo/workspace/runrun-3-mobile/.tmp/pages/timeline/timeline.ngfactory.ts:1531:38 
[19:19:07]  Module ''*'' has no exported member 'Wrapper_ImageViewerDirective'. 
[19:19:07]  Error at 
            /home/nicolas/desarrollo/workspace/runrun-3-mobile/.tmp/pages/comments/comments.ngfactory.ts:1253:38 
[19:19:07]  Module ''*'' has no exported member 'Wrapper_ImageViewerDirective'. 
[19:19:07]  Error at /home/nicolas/desarrollo/workspace/runrun-3-mobile/.tmp/pages/profile/profile.ngfactory.ts:984:38 
[19:19:07]  Module ''*'' has no exported member 'Wrapper_ImageViewerDirective'. 
[19:19:07]  ngc failed 
[19:19:07]  ionic-app-script task: "build" 
[19:19:07]  Error: Error `


Your system information:

> Cordova CLI: 6.3.1 
> Ionic Framework Version: 2.0.0-rc.3
> Ionic CLI Version: 2.1.7
> Ionic App Lib Version: 2.1.4
> Ionic App Scripts Version: 0.0.46
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 3.19
> Node Version: v6.7.0
> Xcode version: Not installed

**Comment by vazad28** [comment]
@niconaso,
I too am seeing the same error. If I use --dev flag in the build its ok but without it I too am seeing this error.

**Comment by SealTecH** [comment]
yea, after update to rc3 I have same error

**Comment by Riron** [comment]
As mentioned [here](https://forum.ionicframework.com/t/ionic-build-module-has-no-exported-member-wrapper-toolbaritem/68439), could you try to remove the `node_modules` directory from your project, and then run `npm install` inside of your project ?

**Comment by niconaso** [comment]
@Riron I followed your steps and finally it works!

**Comment by vazad28** [comment]
@Riron , I tried your suggestion on a new ionic test app as well but still the same error
[17:09:26]  Error: Error at /Users/vik/Developer/IonicFirebase/test/testApp/.tmp/pages/home/home.ngfactory.ts:120:39 
[17:09:26]  Module ''*'' has no exported member 'Wrapper_ImageViewerDirective'. 
[17:09:26]  ngc failed 
[17:09:26]  ionic-app-script task: "build" 
[17:09:26]  Error: Error

**Comment by lingyilun** [comment]
@Riron  1.1.5 works perfect!! Thank you very much!
I  remove the node_modules and then run npm install,
All the problems are solved

Information:
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.0.0
Xcode version: Not installed

**Comment by vazad28** [comment]
Hi, I am just curious (perplexed why it is still not working for me) if this is working without --dev flag or with --dev flag for everyone.

**Comment by lingyilun** [comment]
@vazad28  my package.json working without --dev flag
Is there an error in your app.module.ts?
And you can provide yours system information?

**Comment by vazad28** [comment]
@lingyilun, thank you for following up and offering to help. Here is my ionic info
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.0 Build version 8A218a

If I use --dev flag or use -lc flag it works but not otherwise

**Comment by lingyilun** [comment]
@vazad28  your version of the ionic-img-viewer is 1.1.5?
If version 1.1.3 is required use --dev flag

**Comment by vazad28** [comment]
yes I'm using 1.1.5.

here is a snapshot of the package.json
 "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-img-viewer": "1.1.5",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.46",
    "typescript": "2.0.6"
  },

**Comment by lingyilun** [comment]
@vazad28 You tried Riron said try to remove the node_modules and then run npm install inside of your project?

**Comment by vazad28** [comment]
Yes, I have done that multiple times rather. I tried that on old projects and on new project created with ionic start. Still the same. I re-installed corodova, ionic CLI. At this stage I am clueless as I think I have tried everything. Any other suggestion you may have?

**Comment by dmastag** [comment]
Curious, could you copy the src folder directly into your app and add that in your module compoenent directly?

**Comment by lingyilun** [comment]
Maybe the first use --dev and wait to update is the best way

**Comment by vazad28** [comment]
I copied the src folder from node_modules and place it in the app src folder.
import in app.module.ts as 
import { IonicImageViewerModule } from '../src/ionic-img-viewer';

error...
Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'

**Comment by dmastag** [comment]
@vazad28 that does not seem to be correct.

I put the files into 
`src/components/ionic-img-viewer`


And then in my app.module.ts
```
import { IonicImageViewerModule } from '../components/ionic-img-viewer/module';
```


Is that working?

**Comment by vazad28** [comment]
<img width="479" alt="screen shot 2016-11-23 at 11 53 56 pm" src="https://cloud.githubusercontent.com/assets/4810909/20588094/271b1be4-b1d8-11e6-8c43-d2e9b1ca28ff.png">

here is my app.module.ts

//import { IonicImageViewerModule } from '../src/ionic-img-viewer';
import { IonicImageViewerModule } from '../components/ionic-img-viewer/module';

@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    IonicImageViewerModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}]
})

and error is same
[23:52:37]  Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule' 
[23:52:37]  ngc failed 
[23:52:37]  ionic-app-script task: "build" 
[23:52:37]  Error: Error

**Comment by dmastag** [comment]
Too bad that isn't working for you. Not sure what to suggest now.

**Comment by vazad28** [comment]
I appreciate the help very much. May be some updates in something will fix it, For now will continuw with dev flag. Thanks again.

**Comment by Riron** [comment]
Closing this issue as it should now be fixed and it's getting difficult to follow the thread.
If you experience a similar problem again please open another issue!

**Comment by vazad28** [comment]
Out of blue, this same error came back again.

**Comment by nonren** [comment]
I'm having the same issue now. Any idea how to solve it?

**Comment by tanzeelrana** [comment]
![image](https://cloud.githubusercontent.com/assets/2520028/22364760/b28230c8-e441-11e6-944a-fa55f7615c68.png)


I guess the issue is back ?

**Comment by Riron** [comment]
If the issue comes back, please open another issue and give details about it (like ionic version, plugin version, console error, type of build...).
Thanks.
